spring:
  jpa:
   hibernate.ddl-auto: update
   properties:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
   url: jdbc:mysql://localhost/COVID19?useSSL=false
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-mongo-crud
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${spring.application.name}
  profiles:
    active: local
